### ISSUE TITLE
[BUG] Failed to compile multi-package resource apk

### ISSUE THREAD

**Issue by TimScriptov** [REAndroid/ARSCLib#40]
ApkEditor.jar it shows exactly the same error 

![Screenshot_20230508-163417_APK Editor Pro.png](https://user-images.githubusercontent.com/31324315/236813792-9dd637e8-8910-4e31-962a-8a698c38e1ae.png)

**Comment by TimScriptov** [comment]
App name: MX Player version 1.65.0

https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad

**Comment by REAndroid** [comment]
I confirmed it is bug and I am looking at it.

_This is perfect example apk for multi-package arsc file._

**Comment by REAndroid** [comment]
After I fixed your issue I make some mistake on res config parsing , check the latest [commit](https://github.com/REAndroid/ARSCLib/commit/427e12194fab6dd18341a9926d5aa316c6ab9f2c)

**Comment by TimScriptov** [comment]
Okay, thanks. If possible, I'd like to see the full error. Example: _Source:full/path/AndroidManifest.xml;Message:Unknown attributes name;Line:37;_

**Comment by TimScriptov** [comment]
@REAndroid Thanks, it working!

**Comment by REAndroid** [comment]
> Okay, thanks. If possible, I'd like to see the full error. Example: _Source:full/path/AndroidManifest.xml;Message:Unknown attributes name;Line:37;_
> 
> Or APKLogger
> 
> `public void log(file,message,line){}`

@TimScriptov 
- I did write xml encoding/decoding in a hurry, you can tell it looks like a lazy man coding. I am planning to re-struct the whole xml encoding classes to more neat and understandable to devs. 
- I will do nice error reporting mechanism similar to your suggestion.
- In general keep in mind that ARSCLib do not throw/validate errors as often as ```aapt(2)```  e.g duplicate xml attributes, uncommon type names like instead of ```<string>``` it is also valid to have ``` <blabla name="app_name">My app</blabla> ``` . It will compile whatever but guaranteed to be executable by android os.  This is to give full power to developers, and it is upto devs to decide/validate what is right. 

I would like to comment also on your android app:
- If your app scope is to edit resource, you can do whatever you want without decompiling (like rename package, add/remove values, edit strings, files ... ). I will add ```advanced``` features on [APKEditor](https://github.com/REAndroid/APKEditor) like ```-set-package-name```, ```-set-app-name``` 
- You are not required but please make your app to respect apps protected by [APKEditor](https://github.com/REAndroid/APKEditor) , you can simply use [Util.isProtected(ApkModule);](https://github.com/REAndroid/APKEditor/blob/0325603a721859ab87deadac22ba247e62fa92ef/src/main/java/com/reandroid/apkeditor/Util.java#L118) you can also protect your apps by [Util.addApkEditorInfo(ApkModule, Util.EDIT_TYPE_PROTECTED);](https://github.com/REAndroid/APKEditor/blob/0325603a721859ab87deadac22ba247e62fa92ef/src/main/java/com/reandroid/apkeditor/Util.java#L166)

**Comment by TimScriptov** [comment]
Great news that you want to give more freedom to the developers. Well your mark will remain (protection)

**Comment by TimScriptov** [comment]
Great news that you want to give more freedom to the developers. Well your mark will remain (protect)
